service: alexa-skill-f4

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-layers

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  deploymentBucket: alexa-serverless-bucket
  environment: ${self:custom.constants.ENV}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

custom:
  webpack:
    includeModules: false
    packager: 'yarn'
    webpackConfig: ./webpack.dev.config.js
  prune:
    automatic: true
    number: 1
  serverless-layers:
    packageManager: yarn
  constants: ${file(./env.yml)}

functions:
  alexaHandler:
    handler: src/alexa.handler
    events:
      - alexaSkill: ${self:custom.constants.ALEXA_SKILL}
