service: NOME_DA_MINHA_SKILL

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-layers

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  deploymentBucket: NOME_DO_MEU_BUCKET
  environment: ${self:custom.constants.ENV}

custom:
  webpack:
    includeModules: false
    packager: 'yarn'
    webpackConfig: ./webpack.dev.config.js
  prune:
    automatic: true
    number: 1
  serverless-layers:
    packageManager: yarn
  constants: ${file(./env.yml)}

functions:
  alexaHandler:
    handler: src/alexa.handler
    events:
      - alexaSkill: ${self:custom.constants.ALEXA_SKILL}
